apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.namespace }}
  labels:
    app: pnda
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.roleName }}
  namespace: {{ .Release.namespace }}
  labels:
    app: pnda
rules:
  # TODO check what resources must be granted
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["services"]
    verbs: ["get","watch","create","list","delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["configmaps"]
    verbs: ["get","watch","create","list","delete"]
  - apiGroups: [""]       # "" indicates the core API group
    resources: ["events"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["resourcequotas"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "update", "delete"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["mutatingwebhookconfigurations", "validatingwebhookconfigurations"]
    verbs: ["create", "get", "update", "delete"]
  - apiGroups: ["sparkoperator.k8s.io"]
    resources: ["sparkapplications", "scheduledsparkapplications", "sparkapplications/status", "scheduledsparkapplications/status"]
    verbs: ["*"]
    {{- if .Values.enableBatchScheduler }}
    # This api resources below is configured for the `volcano` batch scheduler.
  - apiGroups: ["scheduling.incubator.k8s.io", "scheduling.sigs.dev"]
    resources: ["podgroups"]
    verbs: ["*"]
    {{- end }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.roleBindingName }}
  namespace: {{ .Release.namespace }}
  labels:
    app: pnda
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccountName }}
    namespace: {{ .Release.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.roleName }}
  apiGroup: rbac.authorization.k8s.io
